### ISSUE TITLE
about the poison attack

### ISSUE THREAD

**Issue by i-hu** [nwpuhkp/DRL-Backdoor-Pong#1]
你好，在论文的伪代码中，当进行投毒攻击时，是先将当前的state进行poison，然后再进行posion_action和poison_reward，但是我在您的代码中主要到您是先进行action和reward，然后对next_state进行poison，感觉是不是顺序有误呢？

**Comment by k4pl3r** [comment]
你好，确实在投毒阶段的前后各一轮出现错位的情况，已简单修改，感谢指正！

**Comment by i-hu** [comment]
请问你现在的研究方向是在做强化学习领域的攻击吗？可否有23年的相关论文进行推荐呢，我检索之后感觉23年的相关论文很少。




@...
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nwpuhkp/DRL-Backdoor-Pong"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月12日(星期四) 下午4:59
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [nwpuhkp/DRL-Backdoor-Pong] about the poison attack (Issue #1)





 
你好，确实在投毒阶段的前后各一轮出现错位的情况，已简单修改，感谢指正！

**Comment by k4pl3r** [comment]
> 请问你现在的研究方向是在做强化学习领域的攻击吗？可否有23年的相关论文进行推荐呢，我检索之后感觉23年的相关论文很少。 @... ***@***.*** &bsp;
> [...](#)
> ------------------原始邮件------------------ 发件人： “nwpuhkp/DRL-Backdoor-Pong” ***@***.***>; 发送时间：&nbsp;2023年10月12日(星期四) 下午4:59 @***.***>; @***.******@***.******@***.***>; 主题：&nbsp;回复：[nwpuhkp/DRL-Backdoor-Pong]关于毒物攻击（问题#1） 你好，确实在投毒阶段的前后各一轮出现错位的情况，已简单修改，感谢指正！ — 直接回复此电子邮件，在 GitHub 上查看或取消订阅。 您收到此消息是因为您创作了线程。消息 ID： ***@***.***>

我最近的研究方向转向了别的问题，对23年的文章没有密切关注了，抱歉
